// <auto-generated />
using System;
using CW_9_S29916.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CW_9_S29916.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523091728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CW_9_S29916.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoctor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDoctor");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            IdDoctor = 1,
                            Email = "doctor1@hospital.com",
                            FirstName = "DoctorFirst1",
                            LastName = "DoctorLast1"
                        },
                        new
                        {
                            IdDoctor = 2,
                            Email = "doctor2@hospital.com",
                            FirstName = "DoctorFirst2",
                            LastName = "DoctorLast2"
                        },
                        new
                        {
                            IdDoctor = 3,
                            Email = "doctor3@hospital.com",
                            FirstName = "DoctorFirst3",
                            LastName = "DoctorLast3"
                        },
                        new
                        {
                            IdDoctor = 4,
                            Email = "doctor4@hospital.com",
                            FirstName = "DoctorFirst4",
                            LastName = "DoctorLast4"
                        },
                        new
                        {
                            IdDoctor = 5,
                            Email = "doctor5@hospital.com",
                            FirstName = "DoctorFirst5",
                            LastName = "DoctorLast5"
                        },
                        new
                        {
                            IdDoctor = 6,
                            Email = "doctor6@hospital.com",
                            FirstName = "DoctorFirst6",
                            LastName = "DoctorLast6"
                        },
                        new
                        {
                            IdDoctor = 7,
                            Email = "doctor7@hospital.com",
                            FirstName = "DoctorFirst7",
                            LastName = "DoctorLast7"
                        },
                        new
                        {
                            IdDoctor = 8,
                            Email = "doctor8@hospital.com",
                            FirstName = "DoctorFirst8",
                            LastName = "DoctorLast8"
                        },
                        new
                        {
                            IdDoctor = 9,
                            Email = "doctor9@hospital.com",
                            FirstName = "DoctorFirst9",
                            LastName = "DoctorLast9"
                        },
                        new
                        {
                            IdDoctor = 10,
                            Email = "doctor10@hospital.com",
                            FirstName = "DoctorFirst10",
                            LastName = "DoctorLast10"
                        },
                        new
                        {
                            IdDoctor = 11,
                            Email = "doctor11@hospital.com",
                            FirstName = "DoctorFirst11",
                            LastName = "DoctorLast11"
                        },
                        new
                        {
                            IdDoctor = 12,
                            Email = "doctor12@hospital.com",
                            FirstName = "DoctorFirst12",
                            LastName = "DoctorLast12"
                        },
                        new
                        {
                            IdDoctor = 13,
                            Email = "doctor13@hospital.com",
                            FirstName = "DoctorFirst13",
                            LastName = "DoctorLast13"
                        },
                        new
                        {
                            IdDoctor = 14,
                            Email = "doctor14@hospital.com",
                            FirstName = "DoctorFirst14",
                            LastName = "DoctorLast14"
                        },
                        new
                        {
                            IdDoctor = 15,
                            Email = "doctor15@hospital.com",
                            FirstName = "DoctorFirst15",
                            LastName = "DoctorLast15"
                        },
                        new
                        {
                            IdDoctor = 16,
                            Email = "doctor16@hospital.com",
                            FirstName = "DoctorFirst16",
                            LastName = "DoctorLast16"
                        },
                        new
                        {
                            IdDoctor = 17,
                            Email = "doctor17@hospital.com",
                            FirstName = "DoctorFirst17",
                            LastName = "DoctorLast17"
                        },
                        new
                        {
                            IdDoctor = 18,
                            Email = "doctor18@hospital.com",
                            FirstName = "DoctorFirst18",
                            LastName = "DoctorLast18"
                        },
                        new
                        {
                            IdDoctor = 19,
                            Email = "doctor19@hospital.com",
                            FirstName = "DoctorFirst19",
                            LastName = "DoctorLast19"
                        },
                        new
                        {
                            IdDoctor = 20,
                            Email = "doctor20@hospital.com",
                            FirstName = "DoctorFirst20",
                            LastName = "DoctorLast20"
                        });
                });

            modelBuilder.Entity("CW_9_S29916.Models.Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicament"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMedicament");

                    b.ToTable("Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            Description = "Description for Medicament 1",
                            Name = "Medicament1",
                            Type = "Type1"
                        },
                        new
                        {
                            IdMedicament = 2,
                            Description = "Description for Medicament 2",
                            Name = "Medicament2",
                            Type = "Type2"
                        },
                        new
                        {
                            IdMedicament = 3,
                            Description = "Description for Medicament 3",
                            Name = "Medicament3",
                            Type = "Type3"
                        },
                        new
                        {
                            IdMedicament = 4,
                            Description = "Description for Medicament 4",
                            Name = "Medicament4",
                            Type = "Type4"
                        },
                        new
                        {
                            IdMedicament = 5,
                            Description = "Description for Medicament 5",
                            Name = "Medicament5",
                            Type = "Type0"
                        },
                        new
                        {
                            IdMedicament = 6,
                            Description = "Description for Medicament 6",
                            Name = "Medicament6",
                            Type = "Type1"
                        },
                        new
                        {
                            IdMedicament = 7,
                            Description = "Description for Medicament 7",
                            Name = "Medicament7",
                            Type = "Type2"
                        },
                        new
                        {
                            IdMedicament = 8,
                            Description = "Description for Medicament 8",
                            Name = "Medicament8",
                            Type = "Type3"
                        },
                        new
                        {
                            IdMedicament = 9,
                            Description = "Description for Medicament 9",
                            Name = "Medicament9",
                            Type = "Type4"
                        },
                        new
                        {
                            IdMedicament = 10,
                            Description = "Description for Medicament 10",
                            Name = "Medicament10",
                            Type = "Type0"
                        },
                        new
                        {
                            IdMedicament = 11,
                            Description = "Description for Medicament 11",
                            Name = "Medicament11",
                            Type = "Type1"
                        },
                        new
                        {
                            IdMedicament = 12,
                            Description = "Description for Medicament 12",
                            Name = "Medicament12",
                            Type = "Type2"
                        },
                        new
                        {
                            IdMedicament = 13,
                            Description = "Description for Medicament 13",
                            Name = "Medicament13",
                            Type = "Type3"
                        },
                        new
                        {
                            IdMedicament = 14,
                            Description = "Description for Medicament 14",
                            Name = "Medicament14",
                            Type = "Type4"
                        },
                        new
                        {
                            IdMedicament = 15,
                            Description = "Description for Medicament 15",
                            Name = "Medicament15",
                            Type = "Type0"
                        },
                        new
                        {
                            IdMedicament = 16,
                            Description = "Description for Medicament 16",
                            Name = "Medicament16",
                            Type = "Type1"
                        },
                        new
                        {
                            IdMedicament = 17,
                            Description = "Description for Medicament 17",
                            Name = "Medicament17",
                            Type = "Type2"
                        },
                        new
                        {
                            IdMedicament = 18,
                            Description = "Description for Medicament 18",
                            Name = "Medicament18",
                            Type = "Type3"
                        },
                        new
                        {
                            IdMedicament = 19,
                            Description = "Description for Medicament 19",
                            Name = "Medicament19",
                            Type = "Type4"
                        },
                        new
                        {
                            IdMedicament = 20,
                            Description = "Description for Medicament 20",
                            Name = "Medicament20",
                            Type = "Type0"
                        });
                });

            modelBuilder.Entity("CW_9_S29916.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatient"));

                    b.Property<DateTime>("Birthdate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPatient");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            IdPatient = 1,
                            Birthdate = new DateTime(1981, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst1",
                            LastName = "PatientLast1"
                        },
                        new
                        {
                            IdPatient = 2,
                            Birthdate = new DateTime(1982, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst2",
                            LastName = "PatientLast2"
                        },
                        new
                        {
                            IdPatient = 3,
                            Birthdate = new DateTime(1983, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst3",
                            LastName = "PatientLast3"
                        },
                        new
                        {
                            IdPatient = 4,
                            Birthdate = new DateTime(1984, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst4",
                            LastName = "PatientLast4"
                        },
                        new
                        {
                            IdPatient = 5,
                            Birthdate = new DateTime(1985, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst5",
                            LastName = "PatientLast5"
                        },
                        new
                        {
                            IdPatient = 6,
                            Birthdate = new DateTime(1986, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst6",
                            LastName = "PatientLast6"
                        },
                        new
                        {
                            IdPatient = 7,
                            Birthdate = new DateTime(1987, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst7",
                            LastName = "PatientLast7"
                        },
                        new
                        {
                            IdPatient = 8,
                            Birthdate = new DateTime(1988, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst8",
                            LastName = "PatientLast8"
                        },
                        new
                        {
                            IdPatient = 9,
                            Birthdate = new DateTime(1989, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst9",
                            LastName = "PatientLast9"
                        },
                        new
                        {
                            IdPatient = 10,
                            Birthdate = new DateTime(1990, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst10",
                            LastName = "PatientLast10"
                        },
                        new
                        {
                            IdPatient = 11,
                            Birthdate = new DateTime(1991, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst11",
                            LastName = "PatientLast11"
                        },
                        new
                        {
                            IdPatient = 12,
                            Birthdate = new DateTime(1992, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst12",
                            LastName = "PatientLast12"
                        },
                        new
                        {
                            IdPatient = 13,
                            Birthdate = new DateTime(1993, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst13",
                            LastName = "PatientLast13"
                        },
                        new
                        {
                            IdPatient = 14,
                            Birthdate = new DateTime(1994, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst14",
                            LastName = "PatientLast14"
                        },
                        new
                        {
                            IdPatient = 15,
                            Birthdate = new DateTime(1995, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst15",
                            LastName = "PatientLast15"
                        },
                        new
                        {
                            IdPatient = 16,
                            Birthdate = new DateTime(1996, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst16",
                            LastName = "PatientLast16"
                        },
                        new
                        {
                            IdPatient = 17,
                            Birthdate = new DateTime(1997, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst17",
                            LastName = "PatientLast17"
                        },
                        new
                        {
                            IdPatient = 18,
                            Birthdate = new DateTime(1998, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst18",
                            LastName = "PatientLast18"
                        },
                        new
                        {
                            IdPatient = 19,
                            Birthdate = new DateTime(1999, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst19",
                            LastName = "PatientLast19"
                        },
                        new
                        {
                            IdPatient = 20,
                            Birthdate = new DateTime(1980, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "PatientFirst20",
                            LastName = "PatientLast20"
                        });
                });

            modelBuilder.Entity("CW_9_S29916.Models.Prescription", b =>
                {
                    b.Property<int>("IdPrescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrescription"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.HasKey("IdPrescription");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            IdPrescription = 1,
                            Date = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 2,
                            Date = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 2,
                            IdPatient = 2
                        },
                        new
                        {
                            IdPrescription = 3,
                            Date = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 3,
                            IdPatient = 3
                        },
                        new
                        {
                            IdPrescription = 4,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 4,
                            IdPatient = 4
                        },
                        new
                        {
                            IdPrescription = 5,
                            Date = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 5,
                            IdPatient = 5
                        },
                        new
                        {
                            IdPrescription = 6,
                            Date = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 6,
                            IdPatient = 6
                        },
                        new
                        {
                            IdPrescription = 7,
                            Date = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 7,
                            IdPatient = 7
                        },
                        new
                        {
                            IdPrescription = 8,
                            Date = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 8,
                            IdPatient = 8
                        },
                        new
                        {
                            IdPrescription = 9,
                            Date = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 9,
                            IdPatient = 9
                        },
                        new
                        {
                            IdPrescription = 10,
                            Date = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 10,
                            IdPatient = 10
                        },
                        new
                        {
                            IdPrescription = 11,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 11,
                            IdPatient = 11
                        },
                        new
                        {
                            IdPrescription = 12,
                            Date = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 12,
                            IdPatient = 12
                        },
                        new
                        {
                            IdPrescription = 13,
                            Date = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 13,
                            IdPatient = 13
                        },
                        new
                        {
                            IdPrescription = 14,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 14,
                            IdPatient = 14
                        },
                        new
                        {
                            IdPrescription = 15,
                            Date = new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 15,
                            IdPatient = 15
                        },
                        new
                        {
                            IdPrescription = 16,
                            Date = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 16,
                            IdPatient = 16
                        },
                        new
                        {
                            IdPrescription = 17,
                            Date = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 17,
                            IdPatient = 17
                        },
                        new
                        {
                            IdPrescription = 18,
                            Date = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 18,
                            IdPatient = 18
                        },
                        new
                        {
                            IdPrescription = 19,
                            Date = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 19,
                            IdPatient = 19
                        },
                        new
                        {
                            IdPrescription = 20,
                            Date = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDoctor = 20,
                            IdPatient = 20
                        });
                });

            modelBuilder.Entity("CW_9_S29916.Models.Prescription_Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .HasColumnType("int");

                    b.Property<int>("IdPrescription")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Dose")
                        .HasColumnType("int");

                    b.HasKey("IdMedicament", "IdPrescription");

                    b.ToTable("Prescription_Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            IdPrescription = 1,
                            Details = "Take 2 times daily",
                            Dose = 2
                        },
                        new
                        {
                            IdMedicament = 2,
                            IdPrescription = 2,
                            Details = "Take 3 times daily",
                            Dose = 3
                        },
                        new
                        {
                            IdMedicament = 3,
                            IdPrescription = 3,
                            Details = "Take 4 times daily",
                            Dose = 4
                        },
                        new
                        {
                            IdMedicament = 4,
                            IdPrescription = 4,
                            Details = "Take 5 times daily",
                            Dose = 5
                        },
                        new
                        {
                            IdMedicament = 5,
                            IdPrescription = 5,
                            Details = "Take 1 times daily",
                            Dose = 1
                        },
                        new
                        {
                            IdMedicament = 6,
                            IdPrescription = 6,
                            Details = "Take 2 times daily",
                            Dose = 2
                        },
                        new
                        {
                            IdMedicament = 7,
                            IdPrescription = 7,
                            Details = "Take 3 times daily",
                            Dose = 3
                        },
                        new
                        {
                            IdMedicament = 8,
                            IdPrescription = 8,
                            Details = "Take 4 times daily",
                            Dose = 4
                        },
                        new
                        {
                            IdMedicament = 9,
                            IdPrescription = 9,
                            Details = "Take 5 times daily",
                            Dose = 5
                        },
                        new
                        {
                            IdMedicament = 10,
                            IdPrescription = 10,
                            Details = "Take 1 times daily",
                            Dose = 1
                        },
                        new
                        {
                            IdMedicament = 11,
                            IdPrescription = 11,
                            Details = "Take 2 times daily",
                            Dose = 2
                        },
                        new
                        {
                            IdMedicament = 12,
                            IdPrescription = 12,
                            Details = "Take 3 times daily",
                            Dose = 3
                        },
                        new
                        {
                            IdMedicament = 13,
                            IdPrescription = 13,
                            Details = "Take 4 times daily",
                            Dose = 4
                        },
                        new
                        {
                            IdMedicament = 14,
                            IdPrescription = 14,
                            Details = "Take 5 times daily",
                            Dose = 5
                        },
                        new
                        {
                            IdMedicament = 15,
                            IdPrescription = 15,
                            Details = "Take 1 times daily",
                            Dose = 1
                        },
                        new
                        {
                            IdMedicament = 16,
                            IdPrescription = 16,
                            Details = "Take 2 times daily",
                            Dose = 2
                        },
                        new
                        {
                            IdMedicament = 17,
                            IdPrescription = 17,
                            Details = "Take 3 times daily",
                            Dose = 3
                        },
                        new
                        {
                            IdMedicament = 18,
                            IdPrescription = 18,
                            Details = "Take 4 times daily",
                            Dose = 4
                        },
                        new
                        {
                            IdMedicament = 19,
                            IdPrescription = 19,
                            Details = "Take 5 times daily",
                            Dose = 5
                        },
                        new
                        {
                            IdMedicament = 20,
                            IdPrescription = 20,
                            Details = "Take 1 times daily",
                            Dose = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
